### ISSUE TITLE
Cloning this repository on Windows

### ISSUE THREAD

**Issue by ThorvaldAagaard** [dealerv2/Dealer-Version-2-#10]
When I clone the repository I get these warnings

![image](https://user-images.githubusercontent.com/10560652/165399070-08061425-4655-4566-a60b-f21d3c1ae840.png)

as windows isn't case sensitive

Will you consider renaming the files (It is preventing git from working, when trying to get latest)

**Comment by dealerv2** [comment]
I have renamed the offending files. and deleted the symlink

**Comment by ThorvaldAagaard** [comment]
Looks like there is still 2 files with the same name
![image](https://user-images.githubusercontent.com/10560652/221452071-036095e3-ba29-449b-a40e-6be2ddf1e3df.png)

Fixed for the other files
