### ISSUE TITLE
Error in documentation

### ISSUE THREAD

**Issue by ThorvaldAagaard** [dealerv2/Dealer-Version-2-#12]
![image](https://user-images.githubusercontent.com/10560652/221450519-e00df1f1-49e5-4c0c-a0ad-9b36f1816ed8.png)

You have moved the files to directory UserEval.
usereval_stub.c  and userval_main.c  no longer exist

![image](https://user-images.githubusercontent.com/10560652/221451763-d0b5a267-b20d-4025-b970-7326e3a98e5b.png)

**Comment by dealerv2** [comment]
The documentation has been corrected.
