### ISSUE TITLE
action print (north, south) prints all the same hands

### ISSUE THREAD

**Issue by MarionMichielsen** [dealerv2/Dealer-Version-2-#13]
After producing several hands, printside (NS) prints a number of different NS hands. 
However print (north, south) prints a number of the same NS hands. 

I am running dealer on windows through linux (have not rebuild)

<img width="381" alt="image" src="https://user-images.githubusercontent.com/91435399/222381829-b6a779ca-efd5-41a7-911c-002c19ec4e79.png">

<img width="219" alt="image" src="https://user-images.githubusercontent.com/91435399/222381943-84e913f1-4d66-4b37-a530-acfb46ad9ceb.png">

**Comment by dealerv2** [comment]
Fixed in latest commit. Premature optimization bug.

**Comment by dealerv2** [comment]
See the file Examples/Descr.prt_dbg for an example of using each of the print actions in dealer.
(Except for the printrpt action which is somewhat different ).
