### ISSUE TITLE
Cant find libgomp.so file

### ISSUE THREAD

**Issue by dealerv2** [dealerv2/Dealer-Version-2-#3]
This issue seems to have come up on the Ubuntu forums in at least one other application.
The solution seems to be to find the library that is needed, and then to create a symlink to it in the correct place.
1) cd to the Prod directory
2) `ldd dealerv2`    -- this will give a list of the dependencies for Dealer. Here is what it shows on my system.
	linux-vdso.so.1 (0x00007ffc2791f000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f2920dcc000)
	**libgomp.so.1 => /usr/lib/x86_64-linux-gnu/libgomp.so.1** (0x00007f2920d8a000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f2920d67000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f2920b85000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f2920a36000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f2920a1b000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f292122b000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f2920a13000)
I interpret this to mean that Dealer expects to see a file called **libgomp.so.1** in the **/usr/lib/x86_64-linux-gnu/**
directory.
this 'file' turns out to be a symlink:
4) `ls -l /usr/lib/x86_64-linux-gnu/libgomp.so.1`
lrwxrwxrwx 1 root root 16 May 29  2021 /usr/lib/x86_64-linux-gnu/libgomp.so.1 -> **libgomp.so.1.0.0**

5) find the real library
`find /usr -name 'libgomp*'`
There will be several results. Some for version 9 of gcc some for other versions some for x64 architecture etc.
/usr/lib/gcc/x86_64-linux-gnu/9/libgomp.a
/usr/lib/gcc/x86_64-linux-gnu/9/libgomp.spec
/usr/lib/gcc/x86_64-linux-gnu/9/libgomp.so
/usr/lib/gcc/x86_64-linux-gnu/8/libgomp.a
/usr/lib/gcc/x86_64-linux-gnu/8/libgomp.spec
/usr/lib/gcc/x86_64-linux-gnu/8/libgomp.so
/usr/lib/llvm-10/lib/libgomp.so
/usr/lib/i386-linux-gnu/libgomp.so.1.0.0
/usr/lib/i386-linux-gnu/libgomp.so.1
**/usr/lib/x86_64-linux-gnu/libgomp.so.1.0.0**
/usr/lib/x86_64-linux-gnu/libgomp.so.1
6) It looks like the generic name, **libgomp.so** needs to point to the real library, on my system **libgomp.so.1.0.0**
So find the real library on your system that matches your version of GCC and architecture (we assume GCC version 9 and 64 bit architecture)  and make certain that the symlink found earlier points to the real library. 
7) issue the symlink command : the syntax is `ln -s symlink real_library`. On my system:
`ln -s /usr/lib/x86_64-linux-gnu/libgomp.so.1  /usr/lib/x86_64-linux-gnu/libgomp.so.1.0.0`

Let me know if this works.

**Comment by ThorvaldAagaard** [comment]
After the make worked for me the program is running fine, so I suggest you close this, as it seems to be a combination of how it is built and how it is executed in my Linux environment

**Comment by dealerv2** [comment]
The repo now builds correctly under WSL. The issue is now closed.
Per the original problem after installing WSL on Windows:
sudo apt update && sudo apt upgrade
sudo apt install make
sudo apt-get install gcc
sudo apt-get install -y bison
sudo apt-get install flex
sudo apt-get install g++
git clone https://github.com/dealerv2/Dealer-Version-2-.git

and it should now build OK.
